### ISSUE TITLE
MyST lexer can't handle code fences with additional backticks

### ISSUE THREAD

**Issue by davidselassie** [simplistix/sybil#111]
The following put in a MyST Markdown file causes a `LexingException`:

``````markdown
`````
this should lex
`````
``````

With the following exception:

```
sybil.exceptions.LexingException: Could not match '(?<=\\n)```(:?\\n|\\Z)' in /home/dsel/test/test.md:
'`````\n'
```

Additional backticks are sometimes needed when you want to [nest directives](https://myst-parser.readthedocs.io/en/latest/syntax/roles-and-directives.html#nesting-directives) or handle literal code that has three backticks.

**Comment by cjw296** [comment]
Can you provide the sybil config you used to generate the above? A full exception would also be helpful...

**Comment by cjw296** [comment]
@davidselassie - this should be fixed now, but I'll hold off releasing for now in the hope we can get #110 done too, but headsup that I'm likely to move onto another project and close that as "won't fix" if I don't hear back soon...

**Comment by cjw296** [comment]
Released here: https://pypi.org/project/sybil/6.1.0/
