### ISSUE TITLE
sdist is missing some files needed for testing

### ISSUE THREAD

**Issue by mtelka** [simplistix/sybil#114]
The sdist package at PyPI is missing some files needed to run tests.  At least `tests/helpers.py` is missing, but maybe more.  Please add missing files to run tests to sdist.  Thank you.

**Comment by cjw296** [comment]
The tests should be run from a checkout the same way the CI does. Why are you trying to run them from an sdist?

**Comment by mtelka** [comment]
Because I'm packaging `sybil` for OpenIndiana and we strongly prefer sdist as a package source.  For now I switched to github tarball, but that does have few drawbacks.  Anyway, if you do not want to have tests in sdist , then why there are `tests/test_*` files there?  I think it would make sense to either have complete tests in sdist, or no test related files at all.

**Comment by cjw296** [comment]
No.
