### ISSUE TITLE
Regression: Fails handling triple backquotes with lang tag

### ISSUE THREAD

**Issue by Marenz** [simplistix/sybil#115]
A docs code example like this:
~~~
        ```python
        sample_code = 1
        ```
~~~
used to work pre 6.1.0. Now I am getting:

~~~
Example at /home/marenz/frequenz/frequenz-client-dispatch-python/src/frequenz/client/dispatch/_client.py, line 64, column 1 did not evaluate as expected:
Pylint validation failed for code example:

sample_code = 1
```
Output: ************* Module dispatch._client
src/frequenz/client/dispatch/_client.py:66:1: E0001: Parsing failed: 'invalid syntax (dispatch._client, line 66)' (syntax-error)

~~~

We use sybil like this:

conftest.py:
```
"""Validate docstring code examples.

Code examples are often wrapped in triple backticks (```) within docstrings.
This plugin extracts these code examples and validates them using pylint.
"""
from frequenz.repo.config.pytest import examples
from sybil import Sybil

pytest_collect_file = Sybil(**examples.get_sybil_arguments()).pytest()
```

examples module: https://github.com/frequenz-floss/frequenz-repo-config-python/blob/v0.x.x/src/frequenz/repo/config/pytest/examples.py

**Comment by Marenz** [comment]
I forgot to add: If I remove the `python` part in my example, it works again

**Comment by Marenz** [comment]
I just realized we do a heavy amount of our own parsing in the linked module.

Specifically [here](https://github.com/frequenz-floss/frequenz-repo-config-python/blob/v0.x.x/src/frequenz/repo/config/pytest/examples.py#L162), we use `example.end` to find the end of the sample and in previous versions that seemed to
match with position before the terminating tripple quotes.

**Comment by cjw296** [comment]
> I forgot to add: If I remove the python part in my example, it works again

Is the example even executed/checked if you do this?

> Specifically [here](https://github.com/frequenz-floss/frequenz-repo-config-python/blob/v0.x.x/src/frequenz/repo/config/pytest/examples.py#L162), we use example.end to find the end of the sample and in previous versions that seemed to match with position before the terminating tripple quotes.

It did, but that was a bug, even appears in the release notes ;-)

**Comment by Marenz** [comment]
> It did, but that was a bug, even appears in the release notes ;-)

I _was_ wondering about that..one persons bug is another persons feature :laughing: 

We're doing that extra parsing because we try to have the original line numbers, but maybe I am just not using some existing features to get the same?

Anyway, closing since it's not a bug, but appreciate any pointers if I can do it better.

**Comment by cjw296** [comment]
Can you try changing this:

```python
        example_code = textwrap.dedent(
            example.document.text[example.start : example.end]
        )
```

to this:

```python
        example_code = example.parsed
```

**Comment by cjw296** [comment]
Am I right in reading your code as _only_ running pylint over the example rather than actually executing the examples?

Getting line numbers right is _hard_, especially if you're modifying the source before executing it. Sybil used to do that style of modification, but I managed to eradicate it by using compile flags instead, partly because getting it right is so hard.

Nonetheless, here's what Sybil does to get this right:

https://github.com/simplistix/sybil/blob/9e125073562d1825bd12add95ed149f85cb71762/sybil/evaluators/python.py#L23-L26

**Comment by Marenz** [comment]
> Am I right in reading your code as only running pylint over the example rather than actually executing the examples?

I mean, executing them fully is certainly desirable, but many of our code requires remote end points for most examples to work :)

I'll try your suggestions as soon as I have some time :) Thanks!

**Comment by Marenz** [comment]
https://github.com/simplistix/sybil/blob/9e125073562d1825bd12add95ed149f85cb71762/sybil/evaluators/python.py#L23-L26
What I don't understand about this code (I do the padding the same), you use `example.parsed`, but that text bit has all the empty lines removed, thus it must also result in wrong line numbers the further you get to the end (more skipped blank lines).

Otherwise that whole hack I did would be obsolete as I could just use `.parsed`.

**Comment by cjw296** [comment]
> you use `example.parsed`, but that text bit has all the empty lines removed

I don't believe this is the case, can you show me an example of `.parsed` having empty lines removed?

> Otherwise that whole hack I did would be obsolete as I could just use .parsed.

That's my hope :-) But, to get the line numbers right, you still have to prefix with the right number of newlines to match where the example was found in the source, and also the number of newlines between the start of the example and the actual line within the example, which is what the code on line 25 above is doing.

**Comment by cjw296** [comment]
I added a test for this in https://github.com/simplistix/sybil/pull/116/files

It appears to show that no blank lines are removed by the MyST `PythonCodeBlockParser`.
Can you confirm this verifies the behaviour is introduced somewhere in your code?

**Comment by Marenz** [comment]
I'll see if I can make a test

**Comment by Marenz** [comment]
https://github.com/simplistix/sybil/pull/117
