### ISSUE TITLE
MyST equivalent for sybil.parsers.rest.DocTestParser

### ISSUE THREAD

**Issue by nstarman** [simplistix/sybil#142]
I'm looking to switch my docs from ReST to MyST. I've been trying to figure out how to have an equivalent to
[sybil.parsers.rest.DocTestParser](https://sybil.readthedocs.io/en/latest/api.html#sybil.parsers.rest.DocTestParser) but for MyST. I don't want to have to wrap all the doctests with  \`\`\`python  ... \`\`\`.
I'm not seeing anything in Sybil currently. How would this be done for markdown? Thanks!

**Comment by cjw296** [comment]
What would you like your examples to look like in MyST?

**Comment by nstarman** [comment]
```
Examples
------—
>>> import x
>>> x.attr
<x.Attribute>
```

**Comment by cjw296** [comment]
Still not really clear what you're trying to achieve, I've attempted to edit your comment above as I'm not sure if your markdown quoting for the github comment was what you intended.

If I guess correctly that, essentially you want _all_ Markdown fenced code blocks to be treated as Python code blocks, you'll probably want to make sure that whatever you're going to use to render your documentation is happy with that.

What are you planning to use to render this markdown and how will you tell it that all these fenced code blocks are Python?

**Comment by nstarman** [comment]
Thanks for the fast response! I've re-edited the above comment to show the difference between the ReST and Myst examples. Using [sybil.parsers.rest.DocTestParser](https://sybil.readthedocs.io/en/latest/api.html#sybil.parsers.rest.DocTestParser) the ReST docstring does not need triple quotes or a code-block directive in order for Sybil to parse the `>>>` as Python. The MyST docstring appears to need a directive because there isn't a direct MyST equivalent to [sybil.parsers.rest.DocTestParser](https://sybil.readthedocs.io/en/latest/api.html#sybil.parsers.rest.DocTestParser). I would appreciate any insight into how to write a `sybil.parsers.myst.DocTestParser`

**Comment by cjw296** [comment]
Have you actually tried rendering your first example with MyST? If that doesn't work that's the first problem you need to solve.

If it renders fine, there's not reason not to use use [sybil.parsers.rest.DocTestParser](https://sybil.readthedocs.io/en/latest/api.html#sybil.parsers.rest.DocTestParser) on your MyST docs. 

This is actually covered in [the docs](https://sybil.readthedocs.io/en/latest/myst.html#doctest):

"""
Alternatively, the ReST [doctest parser](https://sybil.readthedocs.io/en/latest/rest.html#doctest-parser) will find all doctest examples in a Markdown file. If any should not be checked, you can make use of the [skip](https://sybil.readthedocs.io/en/latest/myst.html#myst-skip-parser) parser.
"""

**Comment by nstarman** [comment]
In https://github.com/GalacticDynamics/unxt/pull/216, using the ReST parser works for the MyST docstrings, but it does not work when parsing the markdown docs. This is less of an issue, but I would be interested to solve it for simpler markdown docs.

**Comment by cjw296** [comment]
I'm struggling to follow what you're actually looking for here...
Example [like this](https://github.com/GalacticDynamics/unxt/pull/216/files#diff-209aa00525ee99d0e2487034c324fad17de62595e22ac2a6c0d9b0c30a80d134R25-R32) in that PR look like the normal MyST parsers would be fine.

Where are the examples where that is not the case?

**Comment by cjw296** [comment]
Closing due to lack of followup, we can re-open if required.
