### ISSUE TITLE
Remove `PYTEST_VERSION` constant to work with pytest pre-releases

### ISSUE THREAD

**Issue by Zac-HD** [simplistix/sybil#143]
https://github.com/simplistix/sybil/blob/a06c1646e3545cc1fb221ce9faf36f5ea105be8a/sybil/integration/pytest.py#L21

This breaks for pre-release Pytest versions, with errors like `ValueError: invalid literal for int() with base 10: 'dev127+g5d3a3ac02'`.  I was going to suggest [`pytest.version_tuple`](https://github.com/pytest-dev/pytest/blob/256203a5c9aae87741ca195c29510414dd5ddc73/src/pytest/__init__.py#L7), but it looks like `PYTEST_VERSION` is entirely unused and could thus be deleted without replacement.

**Comment by cjw296** [comment]
Yeah, it's currently unused, but pytest like breaking APIs that Sybil needs to work, so thanks for the pointer to `version_tuple`, I'll use that next time that crops up.

Do you need a release for this?

**Comment by Zac-HD** [comment]
A release would be much appreciated!  I'll be installing from the commit until then 😅

**Comment by cjw296** [comment]
Released in [8.0.1](https://pypi.org/project/sybil/8.0.1/).
