### ISSUE TITLE
Question to test set up: Is it possible that CI is testing the coverage of tests?

### ISSUE THREAD

**Issue by ksuess** [simplistix/sybil#42]
I am not familiar with pytest. IMHO CI is testing the test coverage of tests.
See https://app.circleci.com/pipelines/github/simplistix/sybil/218/workflows/a3f16774-5da5-4ab6-b9f7-f97007b39ab3/jobs/1027/parallel-runs/0/steps/0-103

**Comment by cjw296** [comment]
Let's discuss this on #40, which is where it came up.
