### ISSUE TITLE
"skip" in MyST parser markdown documents

### ISSUE THREAD

**Issue by sscherfke** [simplistix/sybil#44]
According to the [sybil docs](https://sybil.readthedocs.io/en/latest/myst.html#skipping-examples), you can skip exmamples with `; skip ...`.

According to the [MyST parser docs](https://myst-parser.readthedocs.io/en/latest/syntax/syntax.html#comments), comments start with a `%`.

Consequently, MySt does not hide `; skip ...` statements in the output.

I can work around the issue by subclassign the skip parser and setting my own regex that uses `%` instead of `;`.

**Comment by cjw296** [comment]
The inconsistency in Markdown "standards" and parsing is why I'll be sticking with ReST myself.
Anyway, thanks for the report, fixed in 443924abff3ce45abd4987ca306873752bfe2be8!

**Comment by cjw296** [comment]
Released in https://pypi.org/project/sybil/4.0.1/
