### ISSUE TITLE
Markdown forces an empty line at the end

### ISSUE THREAD

**Issue by hynek** [simplistix/sybil#54]
Hi, I've finally come around to try it!

Looks promising, but the following doesn't work:

````
```python
>>> import svc_reg
>>> import uuid

>>> reg = svc_reg.Registry()

>>> reg.register_factory(uuid.UUID, uuid.uuid4)
>>> reg.register_value(str, "Hello World")
```
````

Gives me:

````
Example at /Users/hynek/FOSS/svc-reg/README.md, line 41, column 1 did not evaluate as expected:
Expected:
   ```
Got nothing

README.md:41: SybilFailure
````

While the following does (empty last line):

````
```python
>>> import svc_reg
>>> import uuid

>>> reg = svc_reg.Registry()

>>> reg.register_factory(uuid.UUID, uuid.uuid4)
>>> reg.register_value(str, "Hello World")

```
````

This is not just about None results.

````
```python
>>> container = svc_reg.Container(reg)

>>> u = container.get(uuid.UUID)
>>> u
UUID('...')
>>> # Calling get() again returns the SAME UUID instance!
>>> # Good for DB connections, bad for UUIDs.
>>> u is container.get(uuid.UUID)
True
>>> container.get(str)
'Hello World'
```

````

gives me:

````
Example at /Users/hynek/FOSS/svc-reg/README.md, line 62, column 1 did not evaluate as expected:
Expected:
    'Hello World'
    ```
Got:
    'Hello World'

README.md:62: SybilFailure
````

**Comment by cjw296** [comment]
Hmm, smells like another version of https://github.com/simplistix/sybil/issues/52.
Parsing is hard 😭

**Comment by cjw296** [comment]
Can you share your sybil setup from `conftest.py`?

**Comment by hynek** [comment]
https://github.com/hynek/svc-reg/blob/main/conftest.py 🤓

**Comment by cjw296** [comment]
How come you're using the ReST parsers rather than [sybil.parsers.myst.PythonCodeBlockParser](https://sybil.readthedocs.io/en/latest/api.html#sybil.parsers.myst.PythonCodeBlockParser)?

**Comment by cjw296** [comment]
Added a couple of tests which appear to show this working:
https://github.com/simplistix/sybil/commit/ed027e8c75c2c3b818ddc76249ba9d8144e1aa22

Also chucked in a PR to what I hope will fix things up:
https://github.com/hynek/svc-reg/pull/2

**Comment by hynek** [comment]
> How come you're using the ReST parsers rather than [sybil.parsers.myst.PythonCodeBlockParser](https://sybil.readthedocs.io/en/latest/api.html#sybil.parsers.myst.PythonCodeBlockParser)?

the answer is, as always: copy and paste :D

**Comment by cjw296** [comment]
But from where?

**Comment by hynek** [comment]
I think maybe https://sybil.readthedocs.io/en/latest/patterns.html – I was a bit in a panic mode doing three things at once after fighting my own stuff for a whole day.

**Comment by cjw296** [comment]
Okay, let's move this over to https://github.com/hynek/svc-reg/pull/2, if there are bugs, we can re-open this one, or others
