### ISSUE TITLE
tests/helpers.py not in PyPI tarball

### ISSUE THREAD

**Issue by MeggyCal** [simplistix/sybil#55]
When I download a tarball from PyPi, the tests/ folder contains only test_*.py files, so when I try to run the tests, it fails on missing helpers.py. I can easily workaround the issue by downloading the GitHub tarball and run the tests from there. The building and installation work fine with the PyPI tarball.

Please consider tidying the PyPI tarball, either by completing the testsuite or dropping it entirely (not urgent at all). Thanks!

**Comment by cjw296** [comment]
Hi @MeggyCal, 

What you're doing is neither an advertised nor supported use case, for development instructions, please see:
https://sybil.readthedocs.io/en/latest/development.html

It's not intentional, so a PR to fix would be accepted, but I have no intention of working on this myself.
