### ISSUE TITLE
Feature request: Add type hints

### ISSUE THREAD

**Issue by adamtheturtle** [simplistix/sybil#62]
I see that there is an existing branch for this, https://github.com/simplistix/sybil/tree/typing. Let me know if help is welcome on that. It would be nice to not have to `ignore_missing_imports = true` for `sybil` for strict `mypy` to work on my projects.

**Comment by cjw296** [comment]
Yep, help definitely welcome! Probably worth mentioning that I have a strong preference for avoiding casts and asserts just to appease python's type system.

**Comment by cjw296** [comment]
I think this is all good on master as of [0c2a012](https://github.com/simplistix/sybil/commit/0c2a0123422b9c8110af5ddfdb6ac959a90c68bb), right?

**Comment by adamtheturtle** [comment]
Great, I think that this is close, but just needs https://github.com/simplistix/sybil/pull/102.
