### ISSUE TITLE
ModuleNotFoundError if pytest is not installed

### ISSUE THREAD

**Issue by adamtheturtle** [simplistix/sybil#82]
`pytest` is not defined as a requirement of `sybil`, but `sybil` depends on `pytest`.

* Create a new Python environment
* `pip install sybil==5.0.3`
* Run the following code:

```python
import sybil
sybil.Sybil(parsers=[]).pytest()
```

This raises the error:

```
ModuleNotFoundError: No module named '_pytest'
```

This is not caught by the tests because `pytest` is a test dependency.

I suggest that to fix this, move `pytest` to the install requirements for `sybil`.

FWIW a project like [`pip-check-reqs`](https://pypi.org/project/pip-check-reqs/) would find this issue.

**Comment by cjw296** [comment]
I think this is kindof expected? (ie: if you use the `pytest` integration without installing pytest you get an exception.
I don't want a hard dependency of pytest, and I don't really way to set up a `pip install sybil[pytest]` as I strongly suspect folks will already have `pytest` as a dep before they add Sybil.

**Comment by adamtheturtle** [comment]
Ok, the cost is that there is some complexity in https://github.com/simplistix/sybil/pull/81.
The regular test suite did not catch the initial error there, it is only the docs builder that caught the issue there that showed that an import had to go in `if TYPE_CHECKING` - that seems like a risk, to me.

> I think this is kindof expected?

Not by me, but that might come down to personal experience.

Some reasoning:

* I never expect `ModuleNotFoundError` when using a library
* By adding `pytest` as a requirement, Sybil can specify the versions of `pytest` it is compatible with. This allows `pip` users for example to get an error that they are installing Sybil with an incompatible version of `pytest`.
* If I take a look at some popular libraries that I'm familiar with, which can reasonably expect another dependency to be installed, the ones I've looked at so far all have that other dependency explicitly stated in their requirements.
    * For example, I use [`sphinx-autodoc-typehints`](https://github.com/agronholm/sphinx-autodoc-typehints/blob/main/pyproject.toml#L19) which one would only reasonably use with Sphinx, and it specifies `Sphinx` as a dependency
    * For example, I have used [`flake8-bugbear`](https://github.com/PyCQA/flake8-bugbear/blob/main/pyproject.toml#L39) which one would only reasonably use with flake8, and it specifies flake8 as ad dependency.

**Comment by cjw296** [comment]
How can "pytest is a requirement if and only if you're using the pytest extension" be expressed in `setup.py`? I don't know the answer to that...

To be super clear: Sybil is currently usable without installing `pytest` and I have use cases where that matters, having a hard dependency on `pytest` breaks that, so it is not an acceptable solution.

**Comment by adamtheturtle** [comment]
> How can "pytest is a requirement if and only if you're using the pytest extension" be expressed in setup.py? I don't know the answer to that...

I'm not sure what this means by "using the purest extension", but I'm guessing that it is something that one wouldn't want to do (read source code in the installation process).

Another way that some projects may do this, if they want some functionality to depend on a library but they do not want to add that library as a dependency is to split the project in two. e.g. `pip install sybil`, and `pip install sybil-pytest`.

That said, these are all options with trade-offs which have some pros and cons in terms of simplicity, backwards compatibility, and the use cases where not having `pytest` matters.

**Comment by adamtheturtle** [comment]
> By adding pytest as a requirement, Sybil can specify the versions of pytest it is compatible with. This allows pip users for example to get an error that they are installing Sybil with an incompatible version of pytest.

This is now relevant as Sybil is broken with Pytest 8.0.0.
