### ISSUE TITLE
Request: Add test which fails if `self.evaluator = None` is removed

### ISSUE THREAD

**Issue by adamtheturtle** [simplistix/sybil#88]
`PythonDocument.evaluator` in `sybil/document.py` includes the line `self.evaluator = None`.
`mypy` has issues with this line, and I am trying to resolve those issues.
However, I cannot be confident that my attempts are valid, as I don't understand what this is meant to do, and the tests pass if this line is removed.
My request is that a test is added which fails if this line is removed, so that I can have more confidence.

**Comment by cjw296** [comment]
This ends up going away in the branch I'm currently working on.

**Comment by adamtheturtle** [comment]
Thanks! I'll wait for that
